apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-twitter-tracker
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: twitter-tracker
            image: >-
              docker-registry.default.svc:5000/exist-test/exist-web-test:latest
            command:
              - '/opt/app-root/bin/python'
            args:
              - '/opt/app-root/src/scripts/insert2db/twitter/insert2db.py'
            volumeMounts:
              - name: insert2db-conf
                mountPath: "/opt/app-root/src/scripts/insert2db/conf/"
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: insert2db-conf
            secret:
              secretName: insert2db-conf
